In [1]:
import pandas as pd

counts = pd.read_csv("../data/GSE60450_Lactation-GenewiseCounts.txt", sep="\t")

counts.head()

ModuleNotFoundError: No module named 'pandas'

In [2]:
import pandas as pd

counts = pd.read_csv("../data/GSE60450_Lactation-GenewiseCounts.txt", sep="\t")

counts.head()

ModuleNotFoundError: No module named 'pandas'

In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.22.4 (from pandas)
  Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 8.1 MB/s  0:00:01m0:00:0100:01m
Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.1.post1 tzdata-2025.3

In [1]:
import pandas as pd

counts = pd.read_csv("../data/GSE60450_Lactation-GenewiseCounts.txt", sep="\t")

counts.head()

,EntrezGeneID,Length,MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1,MCL1-DH_BC2CTUACXX_CAGATC_L002_R1,MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1,MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1,MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1,MCL1-DL_BC2CTUACXX_ATCACG_L002_R1,MCL1-LA_BC2CTUACXX_GATCAG_L001_R1,MCL1-LB_BC2CTUACXX_TGACCA_L001_R1,MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1,MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1,MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1,MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1
0,497097,3634,438,300,65,237,354,287,0,0,0,0,0,0
1,100503874,3259,1,0,1,1,0,4,0,0,0,0,0,0
2,100038431,1634,0,0,0,0,0,0,0,0,0,0,0,0
3,19888,9747,1,1,0,0,0,0,10,3,10,2,0,0
4,20671,3130,106,182,82,105,43,82,16,25,18,8,3,10

In [2]:
counts.shape

(27179, 14)

In [3]:
counts.columns

Index(['EntrezGeneID', 'Length', 'MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1',
       'MCL1-DH_BC2CTUACXX_CAGATC_L002_R1',
       'MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1',
       'MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1',
       'MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1',
       'MCL1-DL_BC2CTUACXX_ATCACG_L002_R1',
       'MCL1-LA_BC2CTUACXX_GATCAG_L001_R1',
       'MCL1-LB_BC2CTUACXX_TGACCA_L001_R1',
       'MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1',
       'MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1',
       'MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1',
       'MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1'],
      dtype='object')

In [4]:
counts.head(10)

,EntrezGeneID,Length,MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1,MCL1-DH_BC2CTUACXX_CAGATC_L002_R1,MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1,MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1,MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1,MCL1-DL_BC2CTUACXX_ATCACG_L002_R1,MCL1-LA_BC2CTUACXX_GATCAG_L001_R1,MCL1-LB_BC2CTUACXX_TGACCA_L001_R1,MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1,MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1,MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1,MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1
0,497097,3634,438,300,65,237,354,287,0,0,0,0,0,0
1,100503874,3259,1,0,1,1,0,4,0,0,0,0,0,0
2,100038431,1634,0,0,0,0,0,0,0,0,0,0,0,0
3,19888,9747,1,1,0,0,0,0,10,3,10,2,0,0
4,20671,3130,106,182,82,105,43,82,16,25,18,8,3,10
5,27395,4203,309,234,337,300,290,270,560,464,489,328,307,342
6,18777,2433,652,515,948,935,928,791,826,862,668,646,544,581
7,100503730,799,0,1,0,0,0,0,0,1,2,0,2,2
8,21399,2847,1604,1495,1721,1317,1159,1066,1334,1258,1068,926,508,500
9,58175,2241,4,2,14,4,2,2,170,165,138,60,27,15

In [5]:
counts.shape

(27179, 14)

In [6]:
count_matrix = counts.drop(columns=["EntrezGeneID", "Length"])

count_matrix.head()

,MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1,MCL1-DH_BC2CTUACXX_CAGATC_L002_R1,MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1,MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1,MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1,MCL1-DL_BC2CTUACXX_ATCACG_L002_R1,MCL1-LA_BC2CTUACXX_GATCAG_L001_R1,MCL1-LB_BC2CTUACXX_TGACCA_L001_R1,MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1,MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1,MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1,MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1
0,438,300,65,237,354,287,0,0,0,0,0,0
1,1,0,1,1,0,4,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,10,3,10,2,0,0
4,106,182,82,105,43,82,16,25,18,8,3,10

In [7]:
count_matrix.shape

(27179, 12)

In [8]:
conditions = ["pregnancy"]*6 + ["lactation"]*6
conditions

['pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'lactation',
 'lactation',
 'lactation',
 'lactation',
 'lactation',
 'lactation']

In [9]:
!pip install matplotlib seaborn

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.23 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /home/sudharshini/miniconda3/envs/bioinfo/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 9.1 MB/s  0:00:00m eta 0:00:01
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 8.6 MB/s  0:00:00m eta 0:00:01
Downloading kiwisolver-1.5.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.9 MB/s  0:00:00m eta 0:00:01
Downloading pillow-12.1.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 8.6 MB/s  0:00:00 eta 0:00:01m
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [seaborn]m7/8 [seaborn]ib]
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2 seaborn-0.13.2

In [10]:
count_matrix.shape

(27179, 12)

In [11]:
count_matrix = counts.iloc[:, 2:]

count_matrix.head()

,MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1,MCL1-DH_BC2CTUACXX_CAGATC_L002_R1,MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1,MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1,MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1,MCL1-DL_BC2CTUACXX_ATCACG_L002_R1,MCL1-LA_BC2CTUACXX_GATCAG_L001_R1,MCL1-LB_BC2CTUACXX_TGACCA_L001_R1,MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1,MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1,MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1,MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1
0,438,300,65,237,354,287,0,0,0,0,0,0
1,1,0,1,1,0,4,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,10,3,10,2,0,0
4,106,182,82,105,43,82,16,25,18,8,3,10

In [12]:
count_matrix.shape

(27179, 12)

In [13]:
count_matrix.columns

Index(['MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1',
       'MCL1-DH_BC2CTUACXX_CAGATC_L002_R1',
       'MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1',
       'MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1',
       'MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1',
       'MCL1-DL_BC2CTUACXX_ATCACG_L002_R1',
       'MCL1-LA_BC2CTUACXX_GATCAG_L001_R1',
       'MCL1-LB_BC2CTUACXX_TGACCA_L001_R1',
       'MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1',
       'MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1',
       'MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1',
       'MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1'],
      dtype='object')

In [14]:
samples = count_matrix.columns

conditions = ["pregnancy" if "-D" in s else "lactation" for s in samples]

conditions

['pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'pregnancy',
 'lactation',
 'lactation',
 'lactation',
 'lactation',
 'lactation',
 'lactation']

In [15]:
metadata = pd.DataFrame({
    "sample": samples,
    "condition": conditions
})

metadata

                               sample  condition
0   MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1  pregnancy
1   MCL1-DH_BC2CTUACXX_CAGATC_L002_R1  pregnancy
2   MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1  pregnancy
3   MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1  pregnancy
4   MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1  pregnancy
5   MCL1-DL_BC2CTUACXX_ATCACG_L002_R1  pregnancy
6   MCL1-LA_BC2CTUACXX_GATCAG_L001_R1  lactation
7   MCL1-LB_BC2CTUACXX_TGACCA_L001_R1  lactation
8   MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1  lactation
9   MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1  lactation
10  MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1  lactation
11  MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1  lactation

In [16]:
samples = count_matrix.columns

conditions = ["pregnancy" if "-D" in s else "lactation" for s in samples]

import pandas as pd

metadata = pd.DataFrame({
    "sample": samples,
    "condition": conditions
})

metadata

                               sample  condition
0   MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1  pregnancy
1   MCL1-DH_BC2CTUACXX_CAGATC_L002_R1  pregnancy
2   MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1  pregnancy
3   MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1  pregnancy
4   MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1  pregnancy
5   MCL1-DL_BC2CTUACXX_ATCACG_L002_R1  pregnancy
6   MCL1-LA_BC2CTUACXX_GATCAG_L001_R1  lactation
7   MCL1-LB_BC2CTUACXX_TGACCA_L001_R1  lactation
8   MCL1-LC_BC2CTUACXX_GCCAAT_L001_R1  lactation
9   MCL1-LD_BC2CTUACXX_GGCTAC_L001_R1  lactation
10  MCL1-LE_BC2CTUACXX_TAGCTT_L001_R1  lactation
11  MCL1-LF_BC2CTUACXX_CTTGTA_L001_R1  lactation

In [17]:
count_matrix.to_csv("../data/count_matrix.csv")
metadata.to_csv("../data/metadata.csv", index=False)

In [18]:
ls ~/rnaseq_project/data

GSE60450_Lactation-GenewiseCounts.txt*  count_matrix.csv  metadata.csv